version: '2'
services:
    jhipstersampleapplicationmysql-app:
        image: jhipstersampleapplicationmysql
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipstersampleapplicationmysql-mysql:3306/jhipstersampleapplicationmysql?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipstersampleapplicationmysql-mysql:
        extends:
            file: mysql.yml
            service: jhipstersampleapplicationmysql-mysql
